// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: my.proto

#include "my.pb.h"
#include "my.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace BasicT {

static const char* Tweeter_method_names[] = {
  "/BasicT.Tweeter/SendMessage",
  "/BasicT.Tweeter/GetMessage",
};

std::unique_ptr< Tweeter::Stub> Tweeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Tweeter::Stub> stub(new Tweeter::Stub(channel, options));
  return stub;
}

Tweeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(Tweeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMessage_(Tweeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Tweeter::Stub::SendMessage(::grpc::ClientContext* context, const ::BasicT::TweeterRequest& request, ::BasicT::TweeterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BasicT::TweeterRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void Tweeter::Stub::async::SendMessage(::grpc::ClientContext* context, const ::BasicT::TweeterRequest* request, ::BasicT::TweeterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BasicT::TweeterRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void Tweeter::Stub::async::SendMessage(::grpc::ClientContext* context, const ::BasicT::TweeterRequest* request, ::BasicT::TweeterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BasicT::TweeterReply>* Tweeter::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::BasicT::TweeterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BasicT::TweeterReply, ::BasicT::TweeterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BasicT::TweeterReply>* Tweeter::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::BasicT::TweeterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Tweeter::Stub::GetMessage(::grpc::ClientContext* context, const ::BasicT::LastNTweetsRequest& request, ::BasicT::TweeterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BasicT::LastNTweetsRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMessage_, context, request, response);
}

void Tweeter::Stub::async::GetMessage(::grpc::ClientContext* context, const ::BasicT::LastNTweetsRequest* request, ::BasicT::TweeterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BasicT::LastNTweetsRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMessage_, context, request, response, std::move(f));
}

void Tweeter::Stub::async::GetMessage(::grpc::ClientContext* context, const ::BasicT::LastNTweetsRequest* request, ::BasicT::TweeterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BasicT::TweeterReply>* Tweeter::Stub::PrepareAsyncGetMessageRaw(::grpc::ClientContext* context, const ::BasicT::LastNTweetsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BasicT::TweeterReply, ::BasicT::LastNTweetsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BasicT::TweeterReply>* Tweeter::Stub::AsyncGetMessageRaw(::grpc::ClientContext* context, const ::BasicT::LastNTweetsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

Tweeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Tweeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Tweeter::Service, ::BasicT::TweeterRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Tweeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BasicT::TweeterRequest* req,
             ::BasicT::TweeterReply* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Tweeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Tweeter::Service, ::BasicT::LastNTweetsRequest, ::BasicT::TweeterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Tweeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BasicT::LastNTweetsRequest* req,
             ::BasicT::TweeterReply* resp) {
               return service->GetMessage(ctx, req, resp);
             }, this)));
}

Tweeter::Service::~Service() {
}

::grpc::Status Tweeter::Service::SendMessage(::grpc::ServerContext* context, const ::BasicT::TweeterRequest* request, ::BasicT::TweeterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Tweeter::Service::GetMessage(::grpc::ServerContext* context, const ::BasicT::LastNTweetsRequest* request, ::BasicT::TweeterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace BasicT

